In [1]:
import numpy as np
import pandas as pd

In [2]:
raw_data = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv')

In [3]:
df = raw_data.copy()

In [4]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [5]:
df.dtypes

Area Code         int64
Area             object
Item Code         int64
Item             object
Element Code      int64
Element          object
Unit             object
Y2014           float64
Y2015           float64
Y2016           float64
Y2017           float64
Y2018           float64
dtype: object

In [6]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

### Question Solutions:

##### 11. What is the total sum of Animal Fat produced in 2014 and 2017 respectively?

In [7]:
df.groupby('Item')[['Y2014','Y2017']].sum()

                         Y2014      Y2017
Item
Alcohol, Non-Food      2403.00    2348.00
Alcoholic Beverages  102410.11   95581.06
Animal Products       11935.65   11547.65
Animal fats          209460.54  269617.53
Apples and products    9499.23   10198.90
...                        ...        ...
Vegetables, Other    155038.96  157752.59
Vegetal Products     107145.19  107655.20
Wheat and products   232670.13  240047.62
Wine                   4497.36    4178.02
Yams                 200396.96  229174.59

[119 rows x 2 columns]

##### 12. What is the mean and standard deviation across the whole dataset for the year 2015 to 3 decimal places?

In [8]:
print(f"mean: {(df['Y2015'].mean()):.3f}, std: {(df['Y2015'].std()):.3f}")

mean: 135.236, std: 1603.404

##### 13. What is the mean and standard deviation across the whole dataset for the year 2015 to 3 decimal places?

In [9]:
df['Y2015'].isnull().sum()

1548

In [10]:
round((df['Y2015'].isnull().sum() / df['Y2015'].shape[0] * 100), 2)

2.54

##### 14. Which year had the highest correlation with `Element Code`?

In [11]:
corr_mat = df.corr()

In [12]:
corr_mat

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [13]:
corr_mat['Element Code'].nlargest(2)

Element Code    1.000000
Y2014           0.024457
Name: Element Code, dtype: float64

##### 15. What year has the highest sum of Import Quantity?

In [14]:
element_df = df.groupby('Element')[['Y2014', 'Y2015','Y2016','Y2017','Y2018']].sum()
element_df

,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),10225.56,10235.74,10102.77,10253.84,10258.69
Feed,216927.89,225050.22,228958.65,223705.68,233489.68
Food,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),78718.13,66254.41,69563.68,91645.97,91300.97
Processing,282923.00,287929.00,280631.00,292836.00,308429.00
Production,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,416.00,349.00,89.00,91.00,90.00

In [15]:
# max(element_df[element_df.index == 'Import Quantity'])
max_col = np.argmax(element_df[element_df.index == 'Import Quantity'].values[0])
print(max_col)

3

In [16]:
element_df[element_df.columns[max_col]][element_df.index == 'Import Quantity']

Element
Import Quantity    294559.09
Name: Y2017, dtype: float64

##### 16. What is the total number of the sum of Production in 2014?

In [17]:
element_df['Y2014'][element_df.index == 'Production']

Element
Production    1931287.75
Name: Y2014, dtype: float64

##### 17. Which of these elements had the highest sum in 2018?

In [18]:
element_df[element_df['Y2018'] == max(element_df['Y2018'])]

,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.7,2088198.1,2161192.1

##### 18. Which of these elements had the 3rd lowest sum in 2018?

In [19]:
df.groupby('Element')[['Y2018','Element']].sum()

                                             Y2018
Element
Domestic supply quantity                2161192.10
Export Quantity                          181594.80
Fat supply quantity (g/capita/day)        10258.69
Feed                                     233489.68
Food                                    1303841.28
Food supply (kcal/capita/day)            455261.00
Food supply quantity (kg/capita/yr)       49056.85
Import Quantity                          287997.09
Losses                                   163902.00
Other uses (non-food)                     91300.97
Processing                               308429.00
Production                              2075072.89
Protein supply quantity (g/capita/day)    11833.56
Residuals                                 34864.00
Seed                                      25263.14
Stock Variation                           20577.91
Total Population - Both sexes           1140605.00
Tourist consumption                          90.00

In [20]:
(df.groupby('Element')[['Y2018','Element']].sum())['Y2018'].nsmallest(3)

Element
Tourist consumption                          90.00
Fat supply quantity (g/capita/day)        10258.69
Protein supply quantity (g/capita/day)    11833.56
Name: Y2018, dtype: float64

##### 19. What is the total Import Quantity in Algeria in 2018?

In [21]:
df.groupby(['Area','Element'])['Y2018'].sum().unstack()

Element,Domestic supply quantity,Export Quantity,Fat supply quantity (g/capita/day),Feed,Food,Food supply (kcal/capita/day),Food supply quantity (kg/capita/yr),Import Quantity,Losses,Other uses (non-food),Processing,Production,Protein supply quantity (g/capita/day),Residuals,Seed,Stock Variation,Total Population - Both sexes,Tourist consumption
Area,,,,,,,,,,,,,,,,,,
Algeria,90023.42,811.54,309.09,10668.00,63736.33,13288.0,1509.28,36238.29,7708.0,3970.08,2479.0,60766.67,367.28,630.0,825.00,6172.00,42228.0,NaN
Angola,59590.22,7962.28,230.90,7859.66,37256.56,9538.0,1209.36,7769.67,6135.0,1014.00,6727.0,59039.83,212.20,0.0,595.00,-743.00,30810.0,0.0
Benin,31447.90,729.44,207.82,4662.54,16209.34,11023.0,1411.42,7008.24,2814.0,4192.00,2148.0,27500.54,255.90,-66.0,1487.00,2444.56,11485.0,NaN
Botswana,3045.85,101.68,261.12,28.04,2378.80,9365.0,1055.79,1908.42,106.0,26.02,196.0,1534.10,263.26,300.0,11.00,294.00,2254.0,0.0
Burkina Faso,25705.16,1088.16,264.29,1031.50,20525.63,10951.0,1039.07,2605.64,912.0,262.02,2671.0,24859.68,320.57,-86.0,396.00,674.00,19751.0,NaN
Cabo Verde,731.00,42.99,264.32,48.00,572.99,10164.0,1051.85,499.66,20.0,56.00,12.0,297.36,283.43,0.0,2.00,26.00,544.0,7.0
Cameroon,64009.74,1078.16,217.53,4857.24,35235.51,10929.0,1397.30,4188.88,8742.0,2111.00,12248.0,61293.00,287.57,0.0,819.00,393.00,25216.0,NaN
Central African Republic,5567.06,0.26,242.76,5.00,4457.06,7141.0,955.84,75.02,293.0,48.00,636.0,5601.28,178.29,0.0,131.00,104.00,4666.0,NaN
Chad,15489.73,36.22,211.53,1150.00,9846.69,8457.0,636.12,491.95,1454.0,0.04,1344.0,15386.98,245.98,1410.0,288.00,356.00,15478.0,NaN
Comoros,19.95,0.00,NaN,0.00,12.45,NaN,NaN,2.92,NaN,7.50,NaN,17.02,NaN,NaN,NaN,NaN,NaN,NaN
Congo,8524.55,25.03,181.82,39.66,6281.89,9141.0,1198.66,1785.27,611.0,101.00,1510.0,6960.32,232.33,-34.0,10.00,193.00,5244.0,NaN
C�te d'Ivoire,55557.64,8120.48,237.96,6410.00,32660.63,11110.0,1302.78,9271.21,3931.0,414.01,9537.0,57484.90,230.39,-542.0,3152.00,3071.00,25069.0,NaN
Djibouti,2760.96,1084.00,247.43,298.00,790.96,10779.0,826.88,3784.92,10.0,957.00,0.0,158.05,262.76,706.0,0.00,94.00,959.0,NaN
Egypt,248477.72,9420.24,238.72,25158.30,145135.30,13166.0,1474.48,53954.20,15590.0,6036.12,54035.0,191281.77,390.07,-816.0,3331.00,-12667.00,98424.0,23.0
Eswatini,13158.81,1262.04,189.94,82.00,1217.81,9701.0,1074.56,936.53,682.0,513.00,10685.0,13832.34,248.04,-37.0,14.00,349.00,1136.0,NaN
Ethiopia,107850.72,2138.78,108.49,3669.00,78564.70,9352.0,719.31,5655.24,4531.0,12858.02,6772.0,105976.26,265.34,-20.0,1477.00,1647.00,109224.0,NaN
Ethiopia PDR,0.00,0.00,NaN,0.00,0.00,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN
Gabon,4608.75,16.30,211.75,573.00,2906.75,10531.0,1373.32,1079.75,488.0,77.00,500.0,3507.10,316.46,-2.0,61.00,-27.80,2119.0,NaN
Gambia,2221.89,1390.59,241.96,114.02,1618.88,10128.0,710.09,1212.10,77.0,202.00,172.0,2625.36,262.91,-2.0,38.00,221.00,2280.0,NaN
Ghana,100558.45,4284.86,164.21,14730.28,52540.78,12134.0,1764.99,9914.68,19634.0,7929.38,6316.0,97227.65,246.36,-821.0,221.00,2303.00,29767.0,NaN
Guinea,25292.85,191.61,274.89,4090.00,14310.85,10981.0,1152.87,4707.95,2559.0,608.00,2965.0,21751.50,229.56,533.0,226.00,974.00,12414.0,NaN
Guinea-Bissau,2049.58,156.00,245.35,22.00,1491.58,8916.0,795.77,497.72,159.0,26.00,332.0,1970.49,173.01,0.0,22.00,267.42,1874.0,NaN
Kenya,67202.58,3086.45,191.54,1496.28,50504.48,8781.0,982.67,11188.96,4030.0,841.82,10223.0,59870.92,246.96,-357.0,447.00,770.14,51393.0,17.0
Lesotho,2062.73,80.96,211.10,142.00,1817.72,9288.0,862.41,1016.97,66.0,8.01,17.0,1134.70,266.61,4.0,12.00,11.02,2108.0,NaN
Liberia,4998.99,65.48,196.34,118.00,3802.99,8667.0,789.43,1203.77,338.0,14.00,698.0,3787.70,171.13,-14.0,39.00,-65.00,4819.0,NaN
Madagascar,32596.87,535.81,96.43,2133.60,22116.21,7748.0,842.17,3214.79,2253.0,4221.06,1819.0,30215.86,176.64,-676.0,728.00,293.00,26262.0,NaN
Malawi,50937.37,597.18,161.35,17802.40,23295.97,9566.0,1284.02,520.20,4107.0,608.00,5346.0,52982.34,268.26,-628.0,405.00,1970.00,18143.0,NaN
Mali,40795.02,165.30,235.33,3369.30,25110.72,11492.0,1316.11,1962.06,2616.0,4035.00,3120.0,40926.28,334.30,1979.0,568.00,1924.00,19078.0,NaN
Mauritania,22053.08,36217.88,268.78,63.34,4175.50,11501.0,947.85,3575.74,215.0,17508.24,58.0,55405.01,328.33,0.0,38.00,721.20,4403.0,NaN
Mauritius,8290.36,3387.12,377.28,501.18,1348.03,12198.0,1063.77,1672.39,358.0,46.14,5990.0,10131.08,355.56,-2.0,12.00,124.00,1267.0,31.0
Morocco,86458.07,42429.99,284.16,13679.87,48698.59,13644.0,1351.66,19448.50,4696.0,3205.46,13602.0,111102.59,404.24,861.0,1712.14,1664.00,36029.0,NaN
Mozambique,42581.75,1394.81,195.06,2485.17,29772.57,8404.0,1009.52,5552.03,2159.0,177.00,7843.0,35988.44,169.64,-170.0,309.00,-2432.94,29496.0,NaN
Namibia,4019.66,1712.92,219.81,119.40,2751.26,9871.0,1125.44,1462.04,227.0,748.00,145.0,4167.62,262.98,0.0,30.00,39.91,2448.0,NaN
Niger,31258.84,2017.22,209.32,2389.00,23049.84,10311.0,1027.22,2390.20,3783.0,254.00,1561.0,31812.86,330.36,-1197.0,1416.00,927.00,22443.0,NaN
Nigeria,428323.32,1233.02,218.84,73064.53,243467.65,10285.0,1242.98,21923.38,34951.0,9301.13,27951.0,409877.94,234.45,37486.0,2104.00,2235.00,195875.0,NaN
Rwanda,17426.52,383.64,123.56,96.00,15552.52,8748.0,1264.16,1734.44,1290.0,12.00,420.0,15630.72,236.52,-123.0,184.00,-442.00,12302.0,NaN
Sao Tome and Principe,349.73,10.00,286.54,0.00,254.13,9786.0,1231.72,84.10,28.0,9.60,44.0,276.62,218.05,0.0,2.00,3.00,211.0,12.0
Senegal,19374.64,4451.63,243.21,381.41,13763.22,10186.0,868.16,8005.24,915.0,991.01,3151.0,16359.03,249.27,-98.0,267.00,532.00,15854.0,NaN
Seychelles,10.68,205.14,NaN,4.14,5.58,NaN,NaN,77.71,NaN,0.96,NaN,136.75,NaN,NaN,NaN,1.38,NaN,NaN
Sierra Leone,12753.68,143.90,199.86,2170.00,8444.68,9476.0,1103.94,1659.22,967.0,268.00,818.0,10642.38,204.07,-51.0,129.00,-597.00,7650.0,NaN
South Africa,126493.86,31630.62,331.72,12413.42,61781.13,11589.0,1068.97,16192.45,5576.0,1828.32,45681.0,139882.99,337.47,-1310.0,517.00,-2018.98,57793.0,NaN
Sudan,65451.77,1632.13,263.63,1887.00,41857.77,10309.0,1001.32,9130.11,5221.0,3615.00,12364.0,65336.79,291.87,58.0,451.00,7382.00,41802.0,NaN
Sudan (former),0.00,0.00,NaN,0.00,0.00,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN
Togo,10000.22,809.35,197.24,1171.62,7229.60,9768.0,916.53,3625.48,715.0,234.00,553.0,9308.11,233.85,-230.0,330.00,2121.00,7889.0,NaN
Tunisia,31347.90,1649.87,379.37,5621.70,18901.69,13804.0,1634.21,11030.91,1747.0,346.51,5136.0,23075.85,399.16,-766.0,360.00,1110.00,11565.0,NaN
Uganda,54617.10,4095.70,200.36,297.04,41420.05,7925.0,969.43,3209.87,1707.0,85.02,10886.0,54544.94,187.74,-86.0,314.00,-955.00,42729.0,NaN
United Republic of Tanzania,92239.88,2289.77,214.16,4495.06,65741.38,9487.0,1167.33,1863.68,7538.0,1281.44,11894.0,93182.97,235.74,-169.0,1468.00,521.00,56313.0,NaN
Zambia,24994.80,1011.54,193.83,1950.66,12405.14,8005.0,714.87,990.75,1052.0,147.00,9524.0,24058.60,242.08,-254.0,175.00,-959.00,17352.0,NaN
Zimbabwe,17860.73,416.71,207.99,141.32,8821.37,7627.0,611.22,1673.84,891.0,106.06,8300.0,16161.60,176.57,-546.0,140.00,-447.00,14439.0,NaN

OR

In [22]:
df.pivot_table('Y2018', index='Area', columns='Element', aggfunc='sum')

Element,Domestic supply quantity,Export Quantity,Fat supply quantity (g/capita/day),Feed,Food,Food supply (kcal/capita/day),Food supply quantity (kg/capita/yr),Import Quantity,Losses,Other uses (non-food),Processing,Production,Protein supply quantity (g/capita/day),Residuals,Seed,Stock Variation,Total Population - Both sexes,Tourist consumption
Area,,,,,,,,,,,,,,,,,,
Algeria,90023.42,811.54,309.09,10668.00,63736.33,13288.0,1509.28,36238.29,7708.0,3970.08,2479.0,60766.67,367.28,630.0,825.00,6172.00,42228.0,NaN
Angola,59590.22,7962.28,230.90,7859.66,37256.56,9538.0,1209.36,7769.67,6135.0,1014.00,6727.0,59039.83,212.20,0.0,595.00,-743.00,30810.0,0.0
Benin,31447.90,729.44,207.82,4662.54,16209.34,11023.0,1411.42,7008.24,2814.0,4192.00,2148.0,27500.54,255.90,-66.0,1487.00,2444.56,11485.0,NaN
Botswana,3045.85,101.68,261.12,28.04,2378.80,9365.0,1055.79,1908.42,106.0,26.02,196.0,1534.10,263.26,300.0,11.00,294.00,2254.0,0.0
Burkina Faso,25705.16,1088.16,264.29,1031.50,20525.63,10951.0,1039.07,2605.64,912.0,262.02,2671.0,24859.68,320.57,-86.0,396.00,674.00,19751.0,NaN
Cabo Verde,731.00,42.99,264.32,48.00,572.99,10164.0,1051.85,499.66,20.0,56.00,12.0,297.36,283.43,0.0,2.00,26.00,544.0,7.0
Cameroon,64009.74,1078.16,217.53,4857.24,35235.51,10929.0,1397.30,4188.88,8742.0,2111.00,12248.0,61293.00,287.57,0.0,819.00,393.00,25216.0,NaN
Central African Republic,5567.06,0.26,242.76,5.00,4457.06,7141.0,955.84,75.02,293.0,48.00,636.0,5601.28,178.29,0.0,131.00,104.00,4666.0,NaN
Chad,15489.73,36.22,211.53,1150.00,9846.69,8457.0,636.12,491.95,1454.0,0.04,1344.0,15386.98,245.98,1410.0,288.00,356.00,15478.0,NaN
Comoros,19.95,0.00,NaN,0.00,12.45,NaN,NaN,2.92,NaN,7.50,NaN,17.02,NaN,NaN,NaN,NaN,NaN,NaN
Congo,8524.55,25.03,181.82,39.66,6281.89,9141.0,1198.66,1785.27,611.0,101.00,1510.0,6960.32,232.33,-34.0,10.00,193.00,5244.0,NaN
C�te d'Ivoire,55557.64,8120.48,237.96,6410.00,32660.63,11110.0,1302.78,9271.21,3931.0,414.01,9537.0,57484.90,230.39,-542.0,3152.00,3071.00,25069.0,NaN
Djibouti,2760.96,1084.00,247.43,298.00,790.96,10779.0,826.88,3784.92,10.0,957.00,0.0,158.05,262.76,706.0,0.00,94.00,959.0,NaN
Egypt,248477.72,9420.24,238.72,25158.30,145135.30,13166.0,1474.48,53954.20,15590.0,6036.12,54035.0,191281.77,390.07,-816.0,3331.00,-12667.00,98424.0,23.0
Eswatini,13158.81,1262.04,189.94,82.00,1217.81,9701.0,1074.56,936.53,682.0,513.00,10685.0,13832.34,248.04,-37.0,14.00,349.00,1136.0,NaN
Ethiopia,107850.72,2138.78,108.49,3669.00,78564.70,9352.0,719.31,5655.24,4531.0,12858.02,6772.0,105976.26,265.34,-20.0,1477.00,1647.00,109224.0,NaN
Ethiopia PDR,0.00,0.00,NaN,0.00,0.00,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN
Gabon,4608.75,16.30,211.75,573.00,2906.75,10531.0,1373.32,1079.75,488.0,77.00,500.0,3507.10,316.46,-2.0,61.00,-27.80,2119.0,NaN
Gambia,2221.89,1390.59,241.96,114.02,1618.88,10128.0,710.09,1212.10,77.0,202.00,172.0,2625.36,262.91,-2.0,38.00,221.00,2280.0,NaN
Ghana,100558.45,4284.86,164.21,14730.28,52540.78,12134.0,1764.99,9914.68,19634.0,7929.38,6316.0,97227.65,246.36,-821.0,221.00,2303.00,29767.0,NaN
Guinea,25292.85,191.61,274.89,4090.00,14310.85,10981.0,1152.87,4707.95,2559.0,608.00,2965.0,21751.50,229.56,533.0,226.00,974.00,12414.0,NaN
Guinea-Bissau,2049.58,156.00,245.35,22.00,1491.58,8916.0,795.77,497.72,159.0,26.00,332.0,1970.49,173.01,0.0,22.00,267.42,1874.0,NaN
Kenya,67202.58,3086.45,191.54,1496.28,50504.48,8781.0,982.67,11188.96,4030.0,841.82,10223.0,59870.92,246.96,-357.0,447.00,770.14,51393.0,17.0
Lesotho,2062.73,80.96,211.10,142.00,1817.72,9288.0,862.41,1016.97,66.0,8.01,17.0,1134.70,266.61,4.0,12.00,11.02,2108.0,NaN
Liberia,4998.99,65.48,196.34,118.00,3802.99,8667.0,789.43,1203.77,338.0,14.00,698.0,3787.70,171.13,-14.0,39.00,-65.00,4819.0,NaN
Madagascar,32596.87,535.81,96.43,2133.60,22116.21,7748.0,842.17,3214.79,2253.0,4221.06,1819.0,30215.86,176.64,-676.0,728.00,293.00,26262.0,NaN
Malawi,50937.37,597.18,161.35,17802.40,23295.97,9566.0,1284.02,520.20,4107.0,608.00,5346.0,52982.34,268.26,-628.0,405.00,1970.00,18143.0,NaN
Mali,40795.02,165.30,235.33,3369.30,25110.72,11492.0,1316.11,1962.06,2616.0,4035.00,3120.0,40926.28,334.30,1979.0,568.00,1924.00,19078.0,NaN
Mauritania,22053.08,36217.88,268.78,63.34,4175.50,11501.0,947.85,3575.74,215.0,17508.24,58.0,55405.01,328.33,0.0,38.00,721.20,4403.0,NaN
Mauritius,8290.36,3387.12,377.28,501.18,1348.03,12198.0,1063.77,1672.39,358.0,46.14,5990.0,10131.08,355.56,-2.0,12.00,124.00,1267.0,31.0
Morocco,86458.07,42429.99,284.16,13679.87,48698.59,13644.0,1351.66,19448.50,4696.0,3205.46,13602.0,111102.59,404.24,861.0,1712.14,1664.00,36029.0,NaN
Mozambique,42581.75,1394.81,195.06,2485.17,29772.57,8404.0,1009.52,5552.03,2159.0,177.00,7843.0,35988.44,169.64,-170.0,309.00,-2432.94,29496.0,NaN
Namibia,4019.66,1712.92,219.81,119.40,2751.26,9871.0,1125.44,1462.04,227.0,748.00,145.0,4167.62,262.98,0.0,30.00,39.91,2448.0,NaN
Niger,31258.84,2017.22,209.32,2389.00,23049.84,10311.0,1027.22,2390.20,3783.0,254.00,1561.0,31812.86,330.36,-1197.0,1416.00,927.00,22443.0,NaN
Nigeria,428323.32,1233.02,218.84,73064.53,243467.65,10285.0,1242.98,21923.38,34951.0,9301.13,27951.0,409877.94,234.45,37486.0,2104.00,2235.00,195875.0,NaN
Rwanda,17426.52,383.64,123.56,96.00,15552.52,8748.0,1264.16,1734.44,1290.0,12.00,420.0,15630.72,236.52,-123.0,184.00,-442.00,12302.0,NaN
Sao Tome and Principe,349.73,10.00,286.54,0.00,254.13,9786.0,1231.72,84.10,28.0,9.60,44.0,276.62,218.05,0.0,2.00,3.00,211.0,12.0
Senegal,19374.64,4451.63,243.21,381.41,13763.22,10186.0,868.16,8005.24,915.0,991.01,3151.0,16359.03,249.27,-98.0,267.00,532.00,15854.0,NaN
Seychelles,10.68,205.14,NaN,4.14,5.58,NaN,NaN,77.71,NaN,0.96,NaN,136.75,NaN,NaN,NaN,1.38,NaN,NaN
Sierra Leone,12753.68,143.90,199.86,2170.00,8444.68,9476.0,1103.94,1659.22,967.0,268.00,818.0,10642.38,204.07,-51.0,129.00,-597.00,7650.0,NaN
South Africa,126493.86,31630.62,331.72,12413.42,61781.13,11589.0,1068.97,16192.45,5576.0,1828.32,45681.0,139882.99,337.47,-1310.0,517.00,-2018.98,57793.0,NaN
Sudan,65451.77,1632.13,263.63,1887.00,41857.77,10309.0,1001.32,9130.11,5221.0,3615.00,12364.0,65336.79,291.87,58.0,451.00,7382.00,41802.0,NaN
Sudan (former),0.00,0.00,NaN,0.00,0.00,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN
Togo,10000.22,809.35,197.24,1171.62,7229.60,9768.0,916.53,3625.48,715.0,234.00,553.0,9308.11,233.85,-230.0,330.00,2121.00,7889.0,NaN
Tunisia,31347.90,1649.87,379.37,5621.70,18901.69,13804.0,1634.21,11030.91,1747.0,346.51,5136.0,23075.85,399.16,-766.0,360.00,1110.00,11565.0,NaN
Uganda,54617.10,4095.70,200.36,297.04,41420.05,7925.0,969.43,3209.87,1707.0,85.02,10886.0,54544.94,187.74,-86.0,314.00,-955.00,42729.0,NaN
United Republic of Tanzania,92239.88,2289.77,214.16,4495.06,65741.38,9487.0,1167.33,1863.68,7538.0,1281.44,11894.0,93182.97,235.74,-169.0,1468.00,521.00,56313.0,NaN
Zambia,24994.80,1011.54,193.83,1950.66,12405.14,8005.0,714.87,990.75,1052.0,147.00,9524.0,24058.60,242.08,-254.0,175.00,-959.00,17352.0,NaN
Zimbabwe,17860.73,416.71,207.99,141.32,8821.37,7627.0,611.22,1673.84,891.0,106.06,8300.0,16161.60,176.57,-546.0,140.00,-447.00,14439.0,NaN

##### 20.  What is the total number of unique countries in the dataset?

In [23]:
len(df['Area'].unique())

49